name: Update EPG

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (no history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests pytz
          pip install bs4
          pip install chardet
          
      - name: Run EPG grabber script
        env:
          M3U4U_EPG: ${{ secrets.M3U4U_EPG }}
        run: |
          rm -f daddyliveSchedule.json
          rm -f daily.m3u8
          rm -f daily.xml
          rm -f out.m3u8
          rm -f outworld.m3u8
          rm -f 247channels.html
          rm -f mergeita.m3u8
          rm -f merge.m3u8
          python epg-grabber/getEpgs.py
          python daddyliveSchedule.py
          python daddyscrape.py
          python daddyscrapeworld.py
          python merge.py
          python mergeita.py
          
      - name: Force commit and push the changes (no history)
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update EPG"
          git push --force
